config/routes.rb
Emg::Application.routes.draw do

  resources :complaints

  resources :nerves

  resources :patients do
    resources :rec_sessions 
  end

  resources :rec_sessions do
    resources :measurements
  end

  resources :rec_sessions 
  resources :measurements
  

  root :to => 'home#main'

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  attr_accessible :count, :name
  has_many :session_complaints, :inverse_of =>:complaint
  has_many :rec_sessions, :through => :session_complaints
  def display_name
    "#{self.name} (#{self.session_complaints.size}/#{self.session_complaints.size})"
  end
  
  def self.reference_or_create_by_name( name )
    if name.blank?
      nil
    else
      a = where("lower(name) = ?", name.downcase)
      if a.size > 0
        a[0]
      else
        create(:name=>name)
      end
    end
  end
  
  def self.names
    select("name").collect{|e|e.name}
    
  end
  
  def self.names_with_quot
    select("name").collect{|e|"\"#{e.name}\""}
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  # GET /complaints
  # GET /complaints.json
  def index
    if params[:q].present?
      @complaints = Complaint.where("lower(name) LIKE ?", "%#{params[:q].downcase}%").limit(50)
    else
      @complaints = Complaint.limit(50)
    end

    respond_to do |format|
      format.html  
      format.json { render json: @complaints }
    end
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
    @complaint = Complaint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @complaint }
    end
  end

  # GET /complaints/new
  # GET /complaints/new.json
  def new
    @complaint = Complaint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @complaint }
    end
  end

  # GET /complaints/1/edit
  def edit
    @complaint = Complaint.find(params[:id])
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(params[:complaint])

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render json: @complaint, status: :created, location: @complaint }
      else
        format.html { render action: "new" }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /complaints/1
  # PUT /complaints/1.json
  def update
    @complaint = Complaint.find(params[:id])

    respond_to do |format|
      if @complaint.update_attributes(params[:complaint])
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy

    respond_to do |format|
      format.html { redirect_to complaints_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_for(@complaint) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<h1>Listing complaints</h1>
<div style="text-align:center; ">
<%= form_tag "", :class=>"form-search", :method=>"get" do %>
	<div class="input-append">
	<%= text_field_tag :q, params[:q], :class=>"input-xlarge search-query", placeholder: "" %>
	<%= submit_tag "Search", :class=>"btn" %>
	</div>
<% end %>
</div>
<% if @complaints.size > 0 %>
<ul class="nav nav-tabs nav-stacked">
	<% if params[:q].present? %>
		<p class="text-success" style="text-align:center; ">There are <%= @complaints.size %> results for <%= params[:q] %></p>
	<% end %>
	<% @complaints.each do |complaint| %>
	  <li><%= link_to complaint.display_name, complaint %> </li>
	<% end %>
</ul>
<% else %>
	<p class="text-error" style="text-align:center; ">There are no results for <%= params[:q] %></p>
<% end %>

app/views/complaints/new.html.erb
<h1>New complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @complaint.name %>
</h1>

<ul class="nav nav-tabs nav-stacked">
	<% @complaint.rec_sessions.each do |r| %>
	  <li><a href="<%= url_for(r) %>"><%= raw r.patient.display_name + "<i class='icon-arrow-right'></i>" + r.display_name %> <span class="pull-right">A patient of Dr. </span></a></li>
	<% end %>
</ul>

<%= link_to 'Back', complaints_path, class: "btn" %>