config/routes.rb
Emg::Application.routes.draw do

  resources :complaints

  resources :nerves

  resources :patients do
    resources :rec_sessions 
  end

  resources :rec_sessions do
    resources :measurements
  end

  resources :rec_sessions 
  resources :measurements
  

  root :to => 'home#main'

end

app/models/rec_session.rb
class RecSession < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  
  
  attr_accessible :date, :complaint_1, :session_complaints_attributes, :t_lue, :t_rue, :t_lle, :t_rle
  
  belongs_to :patient, :touch=>true #
  has_many :measurements
  has_many :session_complaints
  has_many :complaints, :through =>:session_complaints, :order=>"id ASC"
  # 
  accepts_nested_attributes_for :session_complaints, :reject_if => proc { |attributes| attributes['complaint_name'].blank? }
  
  def display_name
    "Session #{self.date} " +
  		(self.date.present? ?
  			"(#{ distance_of_time_in_words(self.date , Time.now.beginning_of_day).capitalize} ago)" : "")
  end
  
  def complaints_in_words
    if self.session_complaints.size > 0
      self.session_complaints.collect {|e|e.one_liner}.compact.to_sentence
    else
      "Unspecified complaint"
    end
  end
  
  def report
    self.measurements.joins(:nerve).order("nerves.study_type ASC").collect {|e| e.report}.join(" ")
  end
  
  def temp_in_words
    parts = {t_lue: "LUE", t_rue: "RUE", t_lle: "LLE", t_rle: "RLE"}.collect do |k,v|
      t = self.send(k)
      t ? "#{t} C in the #{v}" : nil
    end
    parts.compact.to_sentence
    
  end
end

app/controllers/rec_sessions_controller.rb
class RecSessionsController < ApplicationController
  # GET /rec_sessions
  # GET /rec_sessions.json
  def index
    @rec_sessions = RecSession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rec_sessions }
    end
  end

  # GET /rec_sessions/1
  # GET /rec_sessions/1.json
  def show
    @rec_session = RecSession.find(params[:id])
    @measurements = @rec_session.measurements.joins(:nerve).select("measurements.*, nerves.study_type as study_type,nerves.name as nerve_name")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rec_session }
    end
  end

  # GET /rec_sessions/new
  # GET /rec_sessions/new.json
  def new
    # @rec_session = RecSession.new
    
    if params[:patient_id]
      @patient = Patient.find(params[:patient_id])
      rec_session = @patient.rec_sessions.create!(:date=>Time.now)
      redirect_to rec_session
    else
      redirect_to root_path
    end
    
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @rec_session }
    # end
  end

  # GET /rec_sessions/1/edit
  def edit
    @rec_session = RecSession.find(params[:id])
    3.times {@rec_session.session_complaints.build}
    
  end

  # POST /rec_sessions
  # POST /rec_sessions.json
  def create
    @rec_session = RecSession.new(params[:rec_session])

    respond_to do |format|
      if @rec_session.save
        format.html { redirect_to @rec_session, notice: 'Rec session was successfully created.' }
        format.json { render json: @rec_session, status: :created, location: @rec_session }
      else
        format.html { render action: "new" }
        format.json { render json: @rec_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rec_sessions/1
  # PUT /rec_sessions/1.json
  def update
    @rec_session = RecSession.find(params[:id])

    respond_to do |format|
      if @rec_session.update_attributes(params[:rec_session])
        format.html { redirect_to @rec_session, notice: 'Rec session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rec_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rec_sessions/1
  # DELETE /rec_sessions/1.json
  def destroy
    @rec_session = RecSession.find(params[:id])
    @rec_session.destroy

    respond_to do |format|
      format.html { redirect_to rec_sessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rec_sessions_helper.rb
module RecSessionsHelper
end

app/views/rec_sessions/_form.html.erb
<%= form_for(@rec_session) do |f| %>
  <% if @rec_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rec_session.errors.count, "error") %> prohibited this rec_session from being saved:</h2>

      <ul>
      <% @rec_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= render "rec_session_fields", :f=> f %>

  <div class="actions">
    <%= f.submit nil,  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rec_sessions/_rec_session_fields.html.erb
<div class="field control-group">
    <%= f.label :date, :class=>"control-label"  %>
	<div class="controls">
	<%= f.date_select :date %>
	</div>
</div>

<%= f.fields_for :session_complaints do |g| %>
	<div class="control-group">
		<%= g.label :complaint_name, "Complaint", :class=>"control-label"  %> 
		<div class="controls">
			<%= g.text_field :complaint_name, "data-provide"=>"typeahead", "data-source"=>"[#{ Complaint.names_with_quot.join(",")}]" %>
			
			<% SessionComplaint.body_parts.each do |s| %>
				<label class="radio inline"><%= s[0] %><%= g.radio_button :body_part, s[1] %></label>
			<% end %>
		</div>
	</div>
<% end %>

app/views/rec_sessions/edit.html.erb
<h1>Editing Rec Session</h1>

<%= render 'form' %>

<%= link_to 'Back', @rec_session, class: "btn" %> 

app/views/rec_sessions/index.html.erb
<h1>Listing rec_sessions</h1>

<table>
  <tr>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rec_sessions.each do |rec_session| %>
  <tr>
    <td><%= rec_session.date %></td>
    <td><%= link_to 'Show', rec_session %></td>
    <td><%= link_to 'Edit', edit_rec_session_path(rec_session) %></td>
    <td><%= link_to 'Destroy', rec_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rec session', new_rec_session_path %>

app/views/rec_sessions/new.html.erb
<h1>New rec_session</h1>

<%= render 'form' %>

<%= link_to 'Back', rec_sessions_path %>

app/views/rec_sessions/show.html.erb
<%= content_for :title do %>
	<%= @rec_session.patient.display_name %> 
<% end %>

<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><%= link_to "Patients", patients_path %> <span class="divider">/</span></li>
  <li><%= link_to @rec_session.patient.display_name, @rec_session.patient %> <span class="divider">/</span></li>
  <li class="active">
	<a href="#"><%= @rec_session.display_name %></a>
  </li>
</ul>

<ul class="pager">
	<li><%= @rec_session.complaints_in_words %></li>
	<li class="next"><%= link_to 'Edit session info', edit_rec_session_path(@rec_session)  %></li>
	<li class="next"><%= link_to 'Add temperature', "#", onclick: "javascript: $('#temp-input-boxes').show(); return false; " %></li>
</ul>

<div class="row-fluid">
	<div class="span12" id="temp-input-boxes" style="display:none; ">
		<div class="well">
		<%= form_for @rec_session, html: {class: "form-inline" } do |h| %>
			<% ["LUE", "RUE", "LLE", "RLE"].each do |loc| %>
			<div class="input-append" style="padding-left: 10px; ">
				<label for="<%= "t_#{loc.downcase}" %>"><%= loc %> 
				<%= h.text_field "t_#{loc.downcase}", {id: "appendedPrependedInput", class: "input-small" } %>			</label>
			  <span class="add-on">&deg;C</span>
			</div>
			<% end %>
			<%= submit_tag "Save", class: "btn" %>
		<% end %>
		</div>
	</div>
</div>
<div class="row-fluid">
<% Nerve.study_types.each do |study_type| %>
	<div class="span4" style="min-height: 130px;">
	<ul class="nav nav-tabs nav-stacked">
		<li class="nav-header"><%= study_type[0] %> </li>
		
		<% @measurements.select {|e|e.study_type.to_i==study_type[1]}.each do |meas| %>
			<li <%= raw "class=\"abnormal\"" if meas.abnormal? or meas.blank? %>><a href="<%= url_for([@rec_session,meas]) %>/edit"><i class="icon-<%= true ? "ok" : "none" %>"></i> <%= meas.display_name %></a></li>
		<% end %>
		<li><a href="<%= rec_session_path + new_measurement_path %>"><i class="icon-plus"></i> <em>Add another</em></a></li>
	</ul>
	</div><%# end .span4 %>
<% end %>
</div><%# end .row-fluid %>

<div class="row-fluid">
	<div class="span12">
		<div class="well">
			<h5>Findings</h5>
			<p>Number of findings: <%= @rec_session.measurements.size %></p>
			<p>Temperature: <%= @rec_session.temp_in_words || "unspecified" %></p>
			<p><%= @rec_session.report %></p>
		</div>
	</div>
</div>