config/routes.rb
Emg::Application.routes.draw do

  resources :complaints

  resources :nerves

  resources :patients do
    resources :rec_sessions 
  end

  resources :rec_sessions do
    resources :measurements
  end

  resources :rec_sessions 
  resources :measurements
  

  root :to => 'home#main'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  
  include ActionView::Helpers::DateHelper
  
  attr_accessible :mrn, :name, :rec_sessions_attributes
  
  has_many :rec_sessions, :dependent=>:destroy
  
  accepts_nested_attributes_for :rec_sessions
  
  def display_name
    "#{self.name}#{ " (#{self.mrn})" if self.mrn.present? }" 
  end
  
  def name_and_mrn
    (self.name) + (self.mrn.present? ? " (#{self.mrn})" : "")
  end
  
  def name
    a = read_attribute(:name) 
    a.present? ? a : "Unnamed patient"
  end
  
  def updated_ago
    # if self.updated_at - Time.now < 7.days
      # self.updated_at.strftime("%Y-%m")
    # else
      time_ago_in_words(self.updated_at) + " ago"
    # end
  end
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    if params[:q].present?
      @patients = Patient.where("lower(name) LIKE ? or mrn LIKE ?", "%" + params[:q].downcase + "%", "%" + params[:q].downcase + "%" ).select("updated_at,name,mrn,id").limit(50)
    else
      @patients = Patient.select("updated_at,name,mrn,id").order("updated_at DESC").limit(30)
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
    # if (r=@patient.rec_sessions).size==1
    #   redirect_to rec_session_path(r.first)
    # else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @patient }
      end
    # end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    session = @patient.rec_sessions.build
    3.times {session.session_complaints.build}
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient.rec_sessions.first || @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient, :html=>{:class=>"form-horizontal"}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li class="alert"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field control-group">
    <%= f.label :name, :class=>"control-label" %>
	<div class="controls">
    <%= f.text_field :name %>
	</div>
  </div>
  <div class="field control-group">
    <%= f.label :mrn, "Record no", :class=>"control-label"  %>
	<div class="controls">
	    <%= f.text_field :mrn %>
	</div>
  </div>

	<% if @patient.new_record? %>

		<div class="well">
			<h2>First recording session info</h2>
			<%= f.fields_for :rec_sessions do |sess| %>
				<%= render "rec_sessions/rec_session_fields", :f=>sess %>
			<% end %>
		</div>
	<% end %>

  <div class="actions">
    <%= f.submit "Save and proceed", :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Back', @patient, class: "btn" %> 

app/views/patients/index.html.erb
<ul class="pager">
	<li><h1>Listing patients</h1></li>
  	<li class="next"><%= link_to 'New Patient', new_patient_path %></li> 
</ul>
<div style="text-align:center">
<%= form_tag "", :class=>"form-search", :method=>"get" do %>
	<div class="input-append">
	<%= text_field_tag :q, params[:q], :class=>"input-xlarge search-query", placeholder: "" %>
	<%= submit_tag "Search", :class=>"btn" %>
	</div>
<% end %>
</div>

<% if @patients.size > 0 %>
	<% if params[:q].present? %>
	<p class="text-success" style="text-align:center; ">There are <%= @patients.size %> results for <%= params[:q] %></p>
	<% end %>
	<ul class="nav nav-tabs nav-stacked">
		<% @patients.each do |patient| %>
			<li>
				<a href="<%= patient_path(patient) %>"><%= patient.name_and_mrn %> <span class="pull-right"><%= patient.updated_ago %></span></a>
			</li>
		<% end %>
	</ul>

<% else %>
	<p class="text-error" style="text-align:center; ">There are no results for <%= params[:q] %></p>
<% end %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

app/views/patients/show.html.erb
<%= content_for :title do %>
	<%= @patient.name_and_mrn %> 
<% end %>


<p id="notice"><%= notice %></p>

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
<li><%= link_to "Patients", patients_path %> <span class="divider">/</span></li>
  <li class="active"><a href="#"><%= @patient.display_name %></a></li>
</ul>

<ul class="pager">
	<li class="next"><%= link_to 'Edit patient', edit_patient_path(@patient) %></li>
	<li class="next"><%= link_to 'Delete patient', @patient, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	<li class="next"><%= link_to "New recording session", patient_path(@patient) + rec_sessions_path + "/new" %></li>
</ul>
<% if @patient.rec_sessions.exists? %>
	<ul class="nav nav-tabs nav-stacked">
		<% @patient.rec_sessions.each do |rec_sessions| %>
		<li><a href="<%= url_for rec_sessions %>"><%=  "Session for #{rec_sessions.complaints_in_words} (#{rec_sessions.measurements.size} measurements)" %><span class="pull-right"><%= rec_sessions.date %></span></a> </li>
		<% end %>
	</ul>
<% else %>
	<p>No recording sessions</p>
<% end %>