config/routes.rb
Emg::Application.routes.draw do

  resources :complaints

  resources :nerves

  resources :patients do
    resources :rec_sessions 
  end

  resources :rec_sessions do
    resources :measurements
  end

  resources :rec_sessions 
  resources :measurements
  

  root :to => 'home#main'

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  attr_accessible :side, :nerve_id, :rec_session_id, :amp_1_cat, :ncv_1_cat, :dist_1_cat, :lat_1_cat, :amp_1, :ncv_1, :dist_1, :lat_1, :amp_2_cat, :ncv_2_cat, :dist_2_cat, :lat_2_cat, :amp_2, :ncv_2, :dist_2, :lat_2, :amp_3_cat, :ncv_3_cat, :dist_3_cat, :lat_3_cat, :amp_3, :ncv_3, :dist_3, :lat_3, :comment
  # :amplitude_cat, :latency_cat, :location_id, :nerve_id, :side, :velocity_cat
  
  belongs_to :rec_session
  belongs_to :nerve
  
  def amp_units
    self.nerve.amp_units
  end
    
  def display_name
    "#{ self.side_abbrev || "" } #{self.nerve ? self.nerve.display_name : ""} #{"(#{self.one_liner})"}"
  end
  
  def lat_in_words( segment_number )
    a = Measurement.latency_choices.rassoc(self.send("lat_#{segment_number}_cat"))
    a ? a[0] : "UNDEFINED"
  end
  
  def amp_in_words( segment_number )
    a = Measurement.amplitude_choices.rassoc(self.send("amp_#{segment_number}_cat"))
    a ? a[0] : "UNDEFINED"    
  end
  
  def ncv_in_words( segment )
    a = Measurement.velocity_choices.rassoc(self.send("ncv_#{segment}_cat"))
    a ? a[0] : "UNDEFINED"
  end
  
  def segment_present?(n)
    [self.send("lat_#{n}_cat"), self.send("amp_#{n}_cat"), self.send("ncv_#{n}_cat")].any? {|e| !(e.nil? or e==0) }
  end
  
  def segments
    nerve = self.nerve
    [1,2,3].select {|e| self.segment_present?(e)}.collect {|n| {:stim_site => nerve ? nerve.stim_site_1 : nil, :amp => self.amp_in_words(n), :ncv => self.ncv_in_words(n), :dist => self.send("dist_#{n}"), :lat=>self.lat_in_words(n)}}
  end
  
  
  def report
    if (nerve=self.nerve)
      # [['Nerve conduction sensory', 1], ['Nerve conduction motor', 2], ["Comparison", 3], ["F response", 4], ["H reflex", 5]]
      case nerve.study_type
      
      when 1 # nerve conduction sensory
        if self.abnormal?
          "#{self.side_in_words} #{nerve.name} sensory potential to #{nerve.rec_site} showed #{self.segments.collect {|e| "#{e[:lat]} peak latency and #{e[:amp]} amplitude at the #{e[:stim_site]} segment" }.to_sentence}. #{self.comment.present? ? "<span id=\"report-comment\">#{self.comment}</span>" : ""}"
        elsif self.blank?
          ""
        else # present and normal          
          "#{self.side_in_words} #{nerve.name} sensory potential to #{nerve.rec_site} showed normal peak latency and normal amplitude."
        end
      when 2 # nerve conduction motor
          "#{self.side_in_words} #{nerve.name} motor potential to #{nerve.rec_site} showed #{self.segments.collect {|e| "#{ e[:lat]} onset latency, #{e[:amp]} amplitude, and #{e[:ncv]} conduction velocity"}.to_sentence}."
        # 3. Abbreviated Motor: {Test_Side list} {Motor_List} motor potential to {Motor_Location_List} showed { Latency_List} onset latency and {Amplitude_List} amplitude. 
        # 4. Abbreviated Motor: Bilateral {Motor_List} motor potential to {Motor_Location_List} showed { Latency_List} onset latencies and {Amplitude_List} amplitudes.
    
      when 3 # comparison studies
        "Comparison studies of #{self.side_in_words} {Sensory_Comparison_List} {Comparison_Location_List} showed a peak latency difference of {entry}ms."
      
      when 4
        "#{self.side_in_words} #{nerve.name} F-waves showed #{self.lat_in_words} latencies."
        # 2. Bilateral {Motor_List} F-waves showed {Latency_List} latencies.  
        
      when 5
        "#{self.side_in_words} #{nerve.name} H-waves showed #{self.lat_in_words} latencies."
          # 2. Bilateral {Motor_List} H-waves showed {Latency_List} latencies.  
      end
    else
      puts "Error in Measurement.report: this measurement does not belong to a nerve #{self.inspect}"
      ""
    end
  end
  
  def blank?
    ![self.lat_1_cat, self.lat_2_cat, self.lat_3_cat, self.amp_1_cat, self.amp_2_cat, self.amp_3_cat, self.ncv_1_cat, self.ncv_2_cat, self.ncv_3_cat].any? {|e| !(e.nil? or e==0) }
  end
  
  def abnormal?
    values = [self.lat_1_cat, self.lat_2_cat, self.lat_3_cat, self.amp_1_cat, self.amp_2_cat, self.amp_3_cat, self.ncv_1_cat, self.ncv_2_cat, self.ncv_3_cat]
    values.include?( 2) or values.include?( 3) or values.include?(4) or values.include?(5)
  end
  
  def one_liner
    if self.abnormal?  
      "Abnormal"
    elsif self.blank?
      "Blank"
    else
      "All normal"
    end
  end
  
  def side_in_words
    { 1 => "Left", 2 => "Right", 3 => "Bilateral"}[self.side] || "UNDEFINED SIDE"
    
  end
  
  def side_abbrev
    { nil => "", 1 => "L", 2 => "R", 3 => "B"}[self.side]
  end
  
  def side=(side_par)
      if side_par =~ /^l/i or [:left,1,"1"].include? side_par
        write_attribute(:side, 1)
      elsif side_par =~ /^r/i or [:right,2,"2"].include? side_par
        write_attribute(:side, 2)
        
      elsif side_par =~ /^b/i or [:bilateral,3,"3"].include? side_par
        write_attribute(:side, 3)
        
      end
      
    end
  
  def self.latency_choices
    [["not measured", 0], ["normal",1], ["borderline",2], ["prolonged",3], ["significantly prolonged",4], ["absent",5]]
  end
  
  def self.amplitude_choices
    [["not measured", 0], ["normal",1], ["reduced",2], ["significantly reduced",3], ["absent",4]]
  end
  
  def self.velocity_choices
    [["not measured", 0], ["normal",1], ["borderline",2], ["decreased",3], ["significantly decreased",4]]
  end
  
  def self.side_choices
    [['Left', 1], ['Right', 2], ["Bilateral",3]]
  end
  
  def self.nerve_sensory_choices
    [["Lateral Antebrachial", 1], ["Lateral Plantar", 2], ["Median", 3], ["Medial Antebrachial", 4], ["Medial Plantar", 5], ["Superficial Peroneal", 6], ["Radial", 7], ["Sural", 8], ["Ulnar",9]]
  end
  
  def self.nerve_motor_choices
    [["Accessory", 10], ["Axillary", 11], ["Facial", 12], ["Femoral", 13], ["Long Thoracic", 14], ["Median", 15], ["Musculocutaneous", 16], ["Peroneal", 17], ["Radial", 18], ["Tibial", 19], ["Ulnar", 20]]
  end
  
  def self.nerve_choices
    Measurement.nerve_sensory_choices.concat( Measurement.nerve_motor_choices)
  end
  
  def self.location_choices
    [['Lisbon', 1], ['Madrid', 2]]
  end
  
    
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @measurements }
    end
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/new
  # GET /measurements/new.json
  def new
    @measurement = Measurement.new(:nerve_id=>params[:nerve_id] )
    @nerve = @measurement.nerve || ( params[:nerve_id].present? ? Nerve.find(params[:nerve_id] ) : nil)
    if @nerve
      @measurement.dist_1 = @nerve.dist_1
      @measurement.dist_2 = @nerve.dist_2
      @measurement.dist_3 = @nerve.dist_3
    end
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @measurement }
    end
  end

  # GET /measurements/1/edit
  def edit
    @measurement = Measurement.find(params[:id])
    @nerve = @measurement.nerve
  end

  # POST /measurements
  # POST /measurements.json
  def create
    if params[:rec_session_id].present?
      @rec_session = RecSession.find(params[:rec_session_id])
      @measurement = @rec_session.measurements.create(params[:measurement])

      respond_to do |format|
        if !@measurement.new_record?
          format.html { redirect_to @rec_session, notice: 'Measurement was successfully created.' }
          format.json { render json: @measurement, status: :created, location: @measurement }
        else
          format.html { render action: "new" }
          format.json { render json: @measurement.errors, status: :unprocessable_entity }
        end
      end
    else
      puts "rec_session_id absent"
      redirect_to root_path
    end
  end

  # PUT /measurements/1
  # PUT /measurements/1.json
  def update
    @measurement = Measurement.find(params[:id])

    respond_to do |format|
      if @measurement.update_attributes(params[:measurement])        
        format.html { redirect_to @measurement.rec_session, notice: 'Measurement was successfully updated.' }
        format.json { head :no_content }
        format.js { render }
      else
        format.html { render action: "edit" }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
        # format.js { render :js => "alert(0)"}
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement = Measurement.find(params[:id])
    @measurement.destroy

    respond_to do |format|
      format.html { redirect_to @measurement.rec_session, notice: "Measurement deleted" }
      format.json { head :no_content }
    end
  end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for([RecSession.find(params[:rec_session_id]), @measurement], html: {class: "form-horizontal"} ) do |f| %>
  <% if @measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% @measurement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field control-group">
	    <%= f.label :side, :class=>"control-label" %>
	    <div class="controls">
			<%= f.select :side, options_for_select(Measurement.side_choices, @measurement.side) %>
	  	</div>
	</div>
	

	<% if params[:nerve_id].blank? and @measurement.nerve_id.blank? %>
		<div class="field control-group">
			<%= f.label :nerve, :class=>"control-label" %>
			<div class="controls">
				<%= f.select :nerve_id, options_for_select(Measurement.nerve_choices   ) %>
			</div>
		</div>
	<% else %>

		<%= f.hidden_field :nerve_id  %>
		

		<% (1..3).each do |n| %>
			<% if @nerve.send("stim_site_#{n}").present? %>
				<div class="well nerve-segment-<%= n %>">
					<div class="pull-right">
						
					<%= link_to "All normal", "#", :class=>"btn", :onclick=>"alert('these buttons do not work yet')" %>
					<%= link_to "Not measured", "#", :class=>"btn", :onclick=>"alert('these buttons do not work yet')" %>
					<%= link_to "Absent", "#", :class=>"btn", :onclick=>"alert('these buttons do not work yet')" %>
					</div>
				  	<h3><%= @nerve.send("stim_site_#{n}") %> <i class="icon-arrow-right"></i> <%= @nerve.rec_site %></h3> 
				<% if @nerve.send("comment_#{n}").present? %> 
					<div><i class="icon-info-sign"></i> <%= @nerve.send("comment_#{n}") %></div>
				<% end %>
					<hr />
					
					<div class="clearfix">
						<% if @nerve.send("dist_#{n}").present? %>
						<div class="span2 center">
						  <p>Distance</p>
							<%= f.text_field "dist_#{n}", :class=>"input-small" %>
							<% if @nerve.send("dist_#{n}").present? %>
						  		<h3 prefix="Ref " suffix="cm"><%= @nerve.send("dist_#{n}") %></h3>
							<% end %>
						</div>
						<% end %>
						
						<% if @nerve.send("lat_#{n}").present? %>
						<div class="span2 center">
						  	<p>Latency</p>
							<%= f.select "lat_#{n}_cat", options_for_select(Measurement.latency_choices, @measurement.send("lat_#{n}_cat")), {}, :class=>"input-medium" %>
							
								<h3 prefix="Ref <" suffix="ms"><%= @nerve.send("lat_#{n}") %></h3>
							
								
							<% if @nerve.send("lat_comment_#{n}").present? %>
								<i class="icon-info-sign"></i> <%= @nerve.send("lat_comment_#{n}") %>
							<% end %>
						</div>
						<% end %>
						
						
						<% if @nerve.send("amp_#{n}").present? %>
						<div class="span2 center">
						  	<p>Amplitude</p>
							<%= f.select "amp_#{n}_cat", options_for_select(Measurement.amplitude_choices, @measurement.send("amp_#{n}_cat")), {}, :class=>"input-medium" %>
							

								<h3 prefix="Ref >" suffix="<%= @nerve.amp_units %>"><%= @nerve.send("amp_#{n}") %></h3>
								
							
							<% if @nerve.send("amp_comment_#{n}").present? %>
								<i class="icon-info-sign"></i> <%= @nerve.send("amp_comment_#{n}") %>
							<% end %>
						</div>
						<% end %>
						
						<% if @nerve.send("ncv").present? %>
						<div class="span2 center">
							
						  	<p>NC Velocity</p>
						<%= f.select "ncv_#{n}_cat", options_for_select(Measurement.velocity_choices, @measurement.send("ncv_#{n}_cat")), {}, :class=>"input-medium" %>
							
								<h3 prefix="Ref >" suffix="m/s"><%= @nerve.send("ncv") %></h3>
							
							<% if @nerve.send("ncv_comment_#{n}").present? %>
								<i class="icon-info-sign"></i> <%= @nerve.send("ncv_comment_#{n}") %>
							<% end %>
						</div>
						<% end %>
					</div>
				</div>
			<% else %>
				
			<% end %><%# end if stim site name is defined for this nerve%>
		<% end %><%# each n %>
	<% end %>

	<div class="alert alert-info">
		<h5>Report</h5>
		<p id="report"><%= raw @measurement.report %></p>
	</div>
	<div>
		<%= f.label :comment, "Comments and additional findings" %>
		<%= f.text_area :comment, :rows=>3, :style=>"width:500px;" %><br /><br />
	</div>
	
	  <div class="actions">
	    <%= f.submit "Save", :class=>"btn btn-primary" %>
	  </div>
	<% end %>

app/views/measurements/edit.html.erb
<%= link_to "Delete", @measurement, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger pull-right" %>
<h1>Edit <%= @nerve.specific_name if @nerve %> measurement</h1>



<%= render 'form' %>

<%= link_to 'Back', @measurement.rec_session %>

app/views/measurements/index.html.erb
<h1>Listing measurements</h1>

<table>
  <tr>
    <th>Side</th>
    <th>Nerve</th>
    <th>Location</th>
    <th>Latency cat</th>
    <th>Amplitude cat</th>
    <th>Velocity cat</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @measurements.each do |measurement| %>
  <tr>
    <td><%= measurement.side %></td>
    <td><%= measurement.nerve_id %></td>
    <td><%= measurement.location_id %></td>
    <td><%= measurement.latency_cat %></td>
    <td><%= measurement.amplitude_cat %></td>
    <td><%= measurement.velocity_cat %></td>
    <td><%= link_to 'Show', measurement %></td>
    <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
    <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<% if params[:nerve_id].blank? %>
	<h1>Choose a nerve</h1>
	<%= render "nerves/selector", :nerve_href_method=>"url_to_new_measurement_for_this_nerve", :nerve_href_params=>params[:rec_session_id] %>
<% else %>
	<h1>New measurement: <%= @nerve.name if @nerve %></h1>
	<h3><%= @nerve.study_type_in_words if @nerve %></h3>
	<%= render "form" %>
	
<% end %>
<%= link_to "Back", params[:rec_session_id].present? ? rec_session_path( params[:rec_session_id] ) : :back, class: "btn" %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Side:</b>
  <%= @measurement.side %>
</p>

<p>
  <b>Nerve:</b>
  <%= @measurement.nerve_id %>
</p>

<p>
  <b>Location:</b>
  <%= @measurement.location_id %>
</p>

<p>
  <b>Latency cat:</b>
  <%= @measurement.latency_cat %>
</p>

<p>
  <b>Amplitude cat:</b>
  <%= @measurement.amplitude_cat %>
</p>

<p>
  <b>Velocity cat:</b>
  <%= @measurement.velocity_cat %>
</p>


<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/update.js.erb
$("#report").html("<%= raw escape_javascript @measurement.report %>")